name: clifford-attractor
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - cctools_osx-64=949.0.1
  - clang=11.0.0
  - clang-11=11.0.0
  - clang_osx-64=11.0.0
  - clangxx=11.0.0
  - clangxx_osx-64=11.0.0
  - compiler-rt=11.0.0
  - compiler-rt_osx-64=11.0.0
  - curl=7.71.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-anaconda=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gettext=0.19.8.1
  - gfortran_impl_osx-64=9.3.0
  - gfortran_osx-64=9.3.0
  - gmp=6.2.1
  - graphite2=1.3.13
  - gsl=2.6
  - harfbuzz=2.7.2
  - icu=67.1
  - isl=0.22.1
  - jpeg=9d
  - krb5=1.17.2
  - ld64_osx-64=530
  - ldid=2.1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp11=11.0.0
  - libcurl=7.71.1
  - libcxx=11.0.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran-devel_osx-64=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.4
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.0.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - llvm-openmp=11.0.0
  - llvm-tools=11.0.0
  - lz4-c=1.9.3
  - make=4.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - ncurses=6.2
  - openjdk=11.0.8
  - openssl=1.1.1i
  - pandoc=2.11.3.2
  - pango=1.42.4
  - pcre=8.44
  - pixman=0.40.0
  - r-askpass=1.0
  - r-assertthat=0.2.1
  - r-backports=1.1.4
  - r-base=3.6.3
  - r-base64enc=0.1_3
  - r-bh=1.69.0_1
  - r-bit=1.1_14
  - r-bit64=0.9_7
  - r-bitops=1.0_6
  - r-blob=1.1.1
  - r-broom=0.5.2
  - r-callr=3.2.0
  - r-catools=1.17.1.2
  - r-cellranger=1.1.0
  - r-cli=1.1.0
  - r-clipr=0.6.0
  - r-colorspace=1.4_1
  - r-config=0.3
  - r-crayon=1.3.4
  - r-curl=3.3
  - r-dbi=1.0.0
  - r-dbplyr=1.4.0
  - r-dichromat=2.0_0
  - r-digest=0.6.18
  - r-dplyr=0.8.0.1
  - r-ellipsis=0.1.0
  - r-evaluate=0.13
  - r-fansi=0.4.0
  - r-forcats=0.4.0
  - r-forge=0.2.0
  - r-fs=1.2.7
  - r-generics=0.0.2
  - r-ggplot2=3.1.1
  - r-glue=1.3.1
  - r-gtable=0.3.0
  - r-haven=2.1.0
  - r-highr=0.8
  - r-hms=0.4.2
  - r-htmltools=0.3.6
  - r-htmlwidgets=1.3
  - r-httpuv=1.5.1
  - r-httr=1.4.0
  - r-jsonlite=1.6
  - r-knitr=1.22
  - r-labeling=0.3
  - r-later=0.8.0
  - r-lattice=0.20_38
  - r-lazyeval=0.2.2
  - r-lubridate=1.7.4
  - r-magrittr=1.5
  - r-markdown=0.9
  - r-mass=7.3_51.3
  - r-matrix=1.2_17
  - r-mgcv=1.8_28
  - r-mime=0.6
  - r-miniui=0.1.1.1
  - r-modelr=0.1.4
  - r-mongolite=2.0.1
  - r-munsell=0.5.0
  - r-nlme=3.1_151
  - r-odbc=1.1.5
  - r-openssl=1.3
  - r-packrat=0.5.0
  - r-pillar=1.3.1
  - r-pkgconfig=2.0.2
  - r-pki=0.1_5.1
  - r-plogr=0.2.0
  - r-plyr=1.8.4
  - r-prettyunits=1.0.2
  - r-processx=3.3.0
  - r-profvis=0.3.5
  - r-progress=1.2.0
  - r-promises=1.0.1
  - r-ps=1.3.0
  - r-purrr=0.3.2
  - r-r2d3=0.2.3
  - r-r6=2.4.0
  - r-rappdirs=0.3.1
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.1
  - r-rcurl=1.95_4.12
  - r-readr=1.3.1
  - r-readxl=1.3.1
  - r-rematch=1.0.1
  - r-reprex=0.2.1
  - r-reshape2=1.4.3
  - r-rjava=0.9_11
  - r-rjdbc=0.2_7.1
  - r-rjsonio=1.3_1.1
  - r-rlang=0.3.4
  - r-rmarkdown=1.12
  - r-rprojroot=1.3_2
  - r-rsconnect=0.8.13
  - r-rstudioapi=0.10
  - r-rvest=0.3.3
  - r-scales=1.0.0
  - r-selectr=0.4_1
  - r-shiny=1.3.2
  - r-sourcetools=0.1.7
  - r-sparklyr=1.0.0
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-sys=3.2
  - r-tibble=2.1.1
  - r-tidyr=0.8.3
  - r-tidyselect=0.2.5
  - r-tidyverse=1.2.1
  - r-tinytex=0.12
  - r-utf8=1.1.4
  - r-viridislite=0.3.0
  - r-whisker=0.3_2
  - r-withr=2.1.2
  - r-xfun=0.6
  - r-xml2=1.2.0
  - r-xtable=1.8_4
  - r-yaml=2.2.0
  - readline=8.0
  - rstudio=1.1.456
  - tapi=1100.0.11
  - tk=8.6.10
  - tktable=2.10
  - unixodbc=2.3.9
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.8
